run:
  go: '1.20'
  tests: false
  concurrency: 8
  skip-dirs:
    - vendor

issues:
  max-issues-per-linter: 0

linters:
  enable-all: true
  disable:
    - wsl
    - tagliatelle # because we want to use_snake case in struct tags
    - exhaustruct
    - gochecknoglobals
    - wrapcheck
    - nilnil
    - depguard
    # Deprecated linters
    - golint
    - nosnakecase
    - exhaustivestruct
    - deadcode
    - varcheck
    - maligned
    - structcheck
    - ifshort
    - scopelint
    - interfacer
    - gofumpt

linters-settings:
  goimports:
    local-prefixes: service2
  gci:
    custom-order: true
    skip-generated: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(service2) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
  godot:
    period: false
  godox:
    keywords:
      - -FIXME
  nlreturn:
    block-size: 5
  varnamelen:
    min-name-length: 1
  nestif:
    min-complexity: 3
  tagliatelle:
    case:
      use-field-name: false
  gocognit:
    min-complexity: 20
  revive:
    enable-all-rules: true
    rules:
      - name: unexported-return
        disabled: true
      - name: blank-imports
        disabled: true
      - name: banned-characters
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: add-constant
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: argument-limit
        arguments: [4]
      - name: cognitive-complexity
        arguments: [12]
      - name: line-length-limit
        arguments: [120]
      - name: function-result-limit
        arguments: [3]
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic